# Redirects
plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Base configuration
permalink: /:title
exclude: [package.json, webpack.config.js, yarn.lock]
highlighter: rouge
timezone: America/New_York
source: docs
destination: docs/_site/design-system

# Organization
org: CFPB
description: CFPB's design system
repository: cfpb/design-system

# Title
title: Design System
name: Design System

# Logo
logourl: assets/img/cfpb-logo.png
logoalt: Consumer Financial Protection Bureau

# We currently don't use this in the templates
subtitle: A set of principles and standards for the Consumer Financial Protection Bureau's design projects.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/design-system'
