for ALIAS in {clipboard,}; do cp activity.svg $ALIAS.svg; done
for ALIAS in {clipboard,}; do cp activity-round.svg $ALIAS-round.svg; done
for ALIAS in {handshake,}; do cp agreement.svg $ALIAS.svg; done
for ALIAS in {handshake,}; do cp agreement-round.svg $ALIAS-round.svg; done
for ALIAS in {public-transit,}; do cp bus.svg $ALIAS.svg; done
for ALIAS in {public-transit,}; do cp bus-round.svg $ALIAS-round.svg; done
for ALIAS in {calculator,}; do cp calculate.svg $ALIAS.svg; done
for ALIAS in {calculator,}; do cp calculate-round.svg $ALIAS-round.svg; done
for ALIAS in {groceries,shopping,shopping-cart,}; do cp cart-round.svg $ALIAS-round.svg; done
for ALIAS in {groceries,shopping,shopping-cart,}; do cp cart.svg $ALIAS.svg; done
for ALIAS in {baby-bottle,}; do cp childcare.svg $ALIAS.svg; done
for ALIAS in {baby-bottle,}; do cp childcare-round.svg $ALIAS-round.svg; done
for ALIAS in {double-quote,}; do cp close-quote.svg $ALIAS.svg; done
for ALIAS in {double-quote,}; do cp close-quote-round.svg $ALIAS-round.svg; done
for ALIAS in {shirt,}; do cp clothes.svg $ALIAS.svg; done
for ALIAS in {shirt,}; do cp clothes-round.svg $ALIAS-round.svg; done
for ALIAS in {gavel,}; do cp court.svg $ALIAS.svg; done
for ALIAS in {gavel,}; do cp court-round.svg $ALIAS-round.svg; done
for ALIAS in {credit-card-payment,}; do cp credit-payment.svg $ALIAS.svg; done
for ALIAS in {credit-card-payment,}; do cp credit-payment-round.svg $ALIAS-round.svg; done
for ALIAS in {document-check,}; do cp credit-report.svg $ALIAS.svg; done
for ALIAS in {document-check,}; do cp credit-report-round.svg $ALIAS-round.svg; done
for ALIAS in {dialog,chat,}; do cp dialogue.svg $ALIAS.svg; done
for ALIAS in {dialog,chat,}; do cp dialogue-round.svg $ALIAS-round.svg; done
for ALIAS in {dining-out,pizza,pizza-slice,food,}; do cp dine-out.svg $ALIAS.svg; done
for ALIAS in {dining-out,pizza,pizza-slice,food,}; do cp dine-out-round.svg $ALIAS-round.svg; done
for ALIAS in {wheelchair,}; do cp disability.svg $ALIAS.svg; done
for ALIAS in {wheelchair,}; do cp disability-round.svg $ALIAS-round.svg; done
for ALIAS in {page,}; do cp document.svg $ALIAS.svg; done
for ALIAS in {page,}; do cp document-round.svg $ALIAS-round.svg; done
for ALIAS in {dollar-sign,cost,}; do cp dollar.svg $ALIAS.svg; done
for ALIAS in {dollar-sign,cost,}; do cp dollar-round.svg $ALIAS-round.svg; done
for ALIAS in {document-down,}; do cp download.svg $ALIAS.svg; done
for ALIAS in {document-down,}; do cp download-round.svg $ALIAS-round.svg; done
for ALIAS in {write,}; do cp edit.svg $ALIAS.svg; done
for ALIAS in {write,}; do cp edit-round.svg $ALIAS-round.svg; done
for ALIAS in {ticket,}; do cp entertainment.svg $ALIAS.svg; done
for ALIAS in {ticket,}; do cp entertainment-round.svg $ALIAS-round.svg; done
for ALIAS in {hammer,tools,}; do cp equipment.svg $ALIAS.svg; done
for ALIAS in {hammer,tools,}; do cp equipment-round.svg $ALIAS-round.svg; done
for ALIAS in {autumn,leaf,}; do cp fall.svg $ALIAS.svg; done
for ALIAS in {autumn,leaf,}; do cp fall-round.svg $ALIAS-round.svg; done
for ALIAS in {sliders,controls,}; do cp filter.svg $ALIAS.svg; done
for ALIAS in {sliders,controls,}; do cp filter-round.svg $ALIAS-round.svg; done
for ALIAS in {garden,}; do cp flower.svg $ALIAS.svg; done
for ALIAS in {garden,}; do cp flower-round.svg $ALIAS-round.svg; done
for ALIAS in {folder-plus,}; do cp folder-add.svg $ALIAS.svg; done
for ALIAS in {folder-plus,}; do cp folder-add-round.svg $ALIAS-round.svg; done
for ALIAS in {folder-x,folder-remove,}; do cp folder-delete.svg $ALIAS.svg; done
for ALIAS in {folder-x,folder-remove,}; do cp folder-delete-round.svg $ALIAS-round.svg; done
for ALIAS in {folder-check,}; do cp folder-save.svg $ALIAS.svg; done
for ALIAS in {folder-check,}; do cp folder-save-round.svg $ALIAS-round.svg; done
for ALIAS in {chair,sofa,}; do cp furniture.svg $ALIAS.svg; done
for ALIAS in {chair,sofa,}; do cp furniture-round.svg $ALIAS-round.svg; done
for ALIAS in {present,package,}; do cp gift.svg $ALIAS.svg; done
for ALIAS in {present,package,}; do cp gift-round.svg $ALIAS-round.svg; done
for ALIAS in {medical,}; do cp health-insurance.svg $ALIAS.svg; done
for ALIAS in {medical,}; do cp health-insurance-round.svg $ALIAS-round.svg; done
for ALIAS in {doctor,}; do cp healthcare.svg $ALIAS.svg; done
for ALIAS in {doctor,}; do cp healthcare-round.svg $ALIAS-round.svg; done
for ALIAS in {horizontal,}; do cp left-right.svg $ALIAS.svg; done
for ALIAS in {horizontal,}; do cp left-right-round.svg $ALIAS-round.svg; done
for ALIAS in {padlock,}; do cp lock.svg $ALIAS.svg; done
for ALIAS in {padlock,}; do cp lock-round.svg $ALIAS-round.svg; done
for ALIAS in {location,}; do cp map.svg $ALIAS.svg; done
for ALIAS in {location,}; do cp map-round.svg $ALIAS-round.svg; done
for ALIAS in {hide,}; do cp minus.svg $ALIAS.svg; done
for ALIAS in {hide,}; do cp minus-round.svg $ALIAS-round.svg; done
for ALIAS in {currency,}; do cp money.svg $ALIAS.svg; done
for ALIAS in {currency,}; do cp money-round.svg $ALIAS-round.svg; done
for ALIAS in {pets,}; do cp pet.svg $ALIAS.svg; done
for ALIAS in {pets,}; do cp pet-round.svg $ALIAS-round.svg; done
for ALIAS in {photography,camera,}; do cp photo.svg $ALIAS.svg; done
for ALIAS in {photography,camera,}; do cp photo-round.svg $ALIAS-round.svg; done
for ALIAS in {saving,savings,}; do cp piggy-bank.svg $ALIAS.svg; done
for ALIAS in {saving,savings,}; do cp piggy-bank-round.svg $ALIAS-round.svg; done
for ALIAS in {show,}; do cp plus.svg $ALIAS.svg; done
for ALIAS in {show,}; do cp plus-round.svg $ALIAS-round.svg; done
for ALIAS in {law,}; do cp policy.svg $ALIAS.svg; done
for ALIAS in {law,}; do cp policy-round.svg $ALIAS-round.svg; done
for ALIAS in {new-window,}; do cp pop-up.svg $ALIAS.svg; done
for ALIAS in {new-window,}; do cp pop-up-round.svg $ALIAS-round.svg; done
for ALIAS in {on-off,}; do cp power.svg $ALIAS.svg; done
for ALIAS in {on-off,}; do cp power-round.svg $ALIAS-round.svg; done
for ALIAS in {prepaid-card,}; do cp prepaid-cards.svg $ALIAS.svg; done
for ALIAS in {prepaid-card,}; do cp prepaid-cards-round.svg $ALIAS-round.svg; done
for ALIAS in {screen,}; do cp presentation.svg $ALIAS.svg; done
for ALIAS in {screen,}; do cp presentation-round.svg $ALIAS-round.svg; done
for ALIAS in {justice,rule,}; do cp regulation.svg $ALIAS.svg; done
for ALIAS in {justice,rule,}; do cp regulation-round.svg $ALIAS-round.svg; done
for ALIAS in {floppy-disk,}; do cp save.svg $ALIAS.svg; done
for ALIAS in {floppy-disk,}; do cp save-round.svg $ALIAS-round.svg; done
for ALIAS in {hand,raise-hand,}; do cp serve.svg $ALIAS.svg; done
for ALIAS in {hand,raise-hand,}; do cp serve-round.svg $ALIAS-round.svg; done
for ALIAS in {dog-tags,}; do cp servicemembers.svg $ALIAS.svg; done
for ALIAS in {dog-tags,}; do cp servicemembers-round.svg $ALIAS-round.svg; done
for ALIAS in {chat-bubble,}; do cp speech-bubble.svg $ALIAS.svg; done
for ALIAS in {chat-bubble,}; do cp speech-bubble-round.svg $ALIAS-round.svg; done
for ALIAS in {sun,}; do cp summer.svg $ALIAS.svg; done
for ALIAS in {sun,}; do cp summer-round.svg $ALIAS-round.svg; done
for ALIAS in {add-page,add-document,}; do cp supplement.svg $ALIAS.svg; done
for ALIAS in {add-page,add-document,}; do cp supplement-round.svg $ALIAS-round.svg; done
for ALIAS in {government,}; do cp taxes.svg $ALIAS.svg; done
for ALIAS in {government,}; do cp taxes-round.svg $ALIAS-round.svg; done
for ALIAS in {thinking,thoughts,}; do cp thought-bubble.svg $ALIAS.svg; done
for ALIAS in {thinking,thoughts,}; do cp thought-bubble-round.svg $ALIAS-round.svg; done
for ALIAS in {airplane,flight,}; do cp travel.svg $ALIAS.svg; done
for ALIAS in {airplane,flight,}; do cp travel-round.svg $ALIAS-round.svg; done
for ALIAS in {vertical,}; do cp up-down.svg $ALIAS.svg; done
for ALIAS in {vertical,}; do cp up-down-round.svg $ALIAS-round.svg; done
for ALIAS in {spinner,}; do cp update.svg $ALIAS.svg; done
for ALIAS in {spinner,}; do cp update-round.svg $ALIAS-round.svg; done
for ALIAS in {document-up,}; do cp upload.svg $ALIAS.svg; done
for ALIAS in {document-up,}; do cp upload-round.svg $ALIAS-round.svg; done
for ALIAS in {movie,camcorder,}; do cp video.svg $ALIAS.svg; done
for ALIAS in {movie,camcorder,}; do cp video-round.svg $ALIAS-round.svg; done
for ALIAS in {exclamation,}; do cp warning.svg $ALIAS.svg; done
for ALIAS in {exclamation,}; do cp warning-round.svg $ALIAS-round.svg; done
for ALIAS in {signal,}; do cp wifi.svg $ALIAS.svg; done
for ALIAS in {signal,}; do cp wifi-round.svg $ALIAS-round.svg; done
for ALIAS in {snow,snowflake,}; do cp winter.svg $ALIAS.svg; done
for ALIAS in {snow,snowflake,}; do cp winter-round.svg $ALIAS-round.svg; done
