import fs from 'node:fs';
import path from 'node:path';

const baseDir = 'packages/cfpb-design-system/src/components/cfpb-icons';
const iconsDir = path.resolve(`${baseDir}/icons`);
const outputJs = path.resolve(`${baseDir}/icons-lib.js`);
const outputCss = path.resolve(`${baseDir}/icons-lib.css`);

/**
 * Convert kebab-case / snake_case file names to camelCase variable names.
 * @param {string} str - an icon file name.
 * @returns {string} A camelCase icon file name.
 */
function toCamelCase(str) {
  return str
    .replace(/[-_]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^(.)/, (_, chr) => chr.toLowerCase());
}

/**
 * Add a fill attribute to SVG markup.
 * @param {string} svg - SVG markup.
 * @param {string} color - The color to put in the fill. Defaults to CFPB gray.
 * @returns {string} SVG markup with fill added.
 */
function addFill(svg, color = 'rgb(90,93,97)') {
  return svg.replace(/<svg([^>]*)>/, `<svg$1 fill="${color}">`);
}

/**
 * Convert SVG markup to a data URI for use in a CSS background-image.
 * @param {string} svg - SVG markup.
 * @returns {string} SVG markup as a data URI.
 */
function svgToDataUrl(svg) {
  // Remove line breaks and extra spaces.
  const cleaned = svg.replace(/\s+/g, ' ').trim();
  // Encode special chars for URL.
  const encoded = encodeURIComponent(cleaned)
    .replace(/'/g, '%27')
    .replace(/'/g, '%22');
  return `url('data:image/svg+xml,${encoded}')`;
}

const files = fs.readdirSync(iconsDir).filter((file) => file.endsWith('.svg'));

const jsExports = [];
const cssVars = [];

files.map((file) => {
  const rawName = path.basename(file, '.svg');
  const name = toCamelCase(rawName);

  const svg = fs
    .readFileSync(path.join(iconsDir, file), 'utf-8')
    .replace(/`/g, '\\`') // Escape backticks so template strings don't break.
    .trim();

  const svgGray = addFill(svg);

  jsExports.push(
    `export const ${name}Icon = \`${svg}\`;`,
    `export const ${name}GrayscaleIcon = \`${svgGray}\`;`,
  );

  cssVars.push(
    `--cfpb-background-icon-svg-${rawName}: ${svgToDataUrl(svg)};`,
    `--cfpb-background-icon-svg-${rawName}-gray: ${svgToDataUrl(svgGray)};`,
  );
});

const jsOutput = `/* AUTO-GENERATED FILE - DO NOT EDIT. Generated by process-icons.js. */

${jsExports.join('\n')}
`;

const cssOutput = `/* AUTO-GENERATED FILE - DO NOT EDIT. Generated by process-icons.js. */
:root {
  ${cssVars.join('\n  ')}
}
`;

fs.writeFileSync(outputJs, jsOutput);
fs.writeFileSync(outputCss, cssOutput);
