name: "Shared action - setup"
runs:
  using: "composite"
  steps:
    - name: Set up Ruby for Jekyll
      uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: 3.4.10

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 26
        cache: yarn

    - name: Install dependencies with Yarn
      shell: bash
      run: |
        yarn install --immutable --immutable-cache
        yarn run after-install
