name: Build dist on main

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

concurrency:
    group: build-dist-on-main
    ## Cancel any in-progress runs of this workflow when a new run is triggered 
    ## Two PR merges close together could start two runs of this workflow, but we only want the latest one to run
    cancel-in-progress: true

jobs:
  build-dist:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          ## grab the full history, maybe shallow checkout is fine here?
          fetch-depth: 0

      - name: Shared setup
        uses:  ./.github/actions/shared-action-setup

      - name: Build generated assets
        run: yarn build

      - name: Commit and push dist
        shell: bash
        run: |
          git config user.name "CFPBot"
          git config user.email "CFPBot@users.noreply.github.com"
          
          git add -f packages/cfpb-design-system/dist

          if git diff --cached --quiet: then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Build dist [skip ci]"
          git push origin HEAD:main
