name: Build dist on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
    group: build-dist-on-main
    ## Cancel any in-progress runs of this workflow when a new run is triggered 
    ## Two commits close together could start two runs of this workflow, but we only want the latest one to run
    cancel-in-progress: true

jobs:
  build-dist:
    # Ignore the workflow's own bot-authored dist commits
    if: github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, 'Build dist assets for commit ')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          ## Grab the full history, maybe shallow checkout is fine here?
          fetch-depth: 0

      - name: Shared setup
        uses:  ./.github/actions/shared-action-setup

      - name: Build tokens
        run: yarn tokens  

      - name: Build generated assets
        run: yarn build

      - name: Commit and push dist
        shell: bash
        run: |
          git config user.name "CFPBot"
          git config user.email "CFPBot@users.noreply.github.com"
          
          git add -f packages/cfpb-design-system/dist

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Build dist assets for commit ${{ github.sha }} [skip ci]"
          git push origin HEAD:main
