name: Lint check

on: 
    pull_request:
        branches: [main]

permissions: 
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install dependencies with Yarn
              run: |
                corepack enable
                yarn install --immutable

            - name: Run lint check
              run: yarn lint:check
