name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    ## !startsWith needs to stay in sync with build-dist-on-main.yml commit message prefix
    if: "${{ github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, 'Build dist assets for commit ') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Shared setup
        uses:  ./.github/actions/shared-action-setup

      - name: Update GitHub pages
        run: ./scripts/update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
