name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Shared setup
        uses:  ./.github/actions/shared-action-setup

      - name: Update GitHub pages
        run: ./scripts/update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
