name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.actor != 'github-actions[bot]' && github.event.head_commit.message != 'Build dist [skip ci]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Shared setup
        uses:  ./.github/actions/shared-action-setup

      - name: Update GitHub pages
        run: ./scripts/update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
